name:                guacamole
version:             0.1.0.0
github:              "avnik/guacamole"
license:             BSD3
author:              "Author name here"
maintainer:          "avn@avnik.info"
copyright:           "2018 Alexander V. Nikolaev"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/avnik/guacamole#readme>

dependencies:
- base >= 4.7 && < 5
- attoparsec
- bytestring
- generics-sop
- mtl
- scientific
- text
- transformers 
- universum

default-extensions: 
- LambdaCase
- NamedFieldPuns
- NoImplicitPrelude
- OverloadedStrings

library:
  source-dirs: src
  ghc-options:
      - -fprint-explicit-kinds

executables:
  guacamole-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - guacamole

tests:
  guacamole-test:
    main:                Test.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - guacamole

    - HUnit
    - hedgehog
    - tasty
    - tasty-discover     >= 4.1.1
    - tasty-hedgehog
    - tasty-hunit

